spring:
  profiles:
    active: sit
---
spring:
  mail:
    username: myapwintnus@gmail.com
    password : mqesmczmfsergwpp
    debug: false
    host: smtp.gmail.com
    port: 25
    properties:
      mail:
        protocol: smtp
        smtp:
          ssl:
            enable: false
            trust: "*"
          auth: false
          starttls:
            enable: true
            required: false
  freemarker:
    template-loader-path: classpath:/ftl
    suffix: .ftl
    checkTemplateLocation: false
  config:
    activate:
      on-profile: sit
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tom
    username: postgres
    password: admin
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    enable_lazy_load_no_trans : true
  #front end using Thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: "TOM"

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port

jwt:
  secret: "appSecretKey"
  expirationMs: 86400000
message: "dev environment"

#leave balance configuration
leave:
  mapping :
    annual: 14
    mc: 14
    cc: 2
    marriage: 4
    hospitalized: 60

user:
  activateUrl: http://localhost:8080/updatePasswordPage/

recommend:
  policy: "project.priority < 3"



---
spring:
  mail:
    username: myapwintnus@gmail.com
    password: mqesmczmfsergwpp
    debug: false
    host: smtp.gmail.com
    port: 25
    properties:
      mail:
        protocol: smtp
        smtp:
          ssl:
            enable: false
            trust: "*"
          auth: false
          starttls:
            enable: true
            required: false
  freemarker:
    template-loader-path: classpath:/ftl
    suffix: .ftl
    checkTemplateLocation: false
  config:
    activate:
      on-profile: staging
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tom-stag-rd.cpih5nqynn3w.ap-southeast-1.rds.amazonaws.com/tom_stag_rd
    username: postgres
    password: password
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port
jwt:
  secret: "appSecretKey"
  expirationMs: 86400000
message: "staging environment"

#leave balance configuration
leave:
  mapping :
    annual: 14
    mc: 14
    cc: 2
    marriage: 4
    hospitalized: 60

user:
  activateUrl: http://localhost:8080/updatePasswordPage/

recommend:
  policy: "project.priority < 3"